# Generated by Django 4.1.3 on 2024-06-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group6', '0002_alter_faq_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
    ]
